# Generated by Django 3.2.17 on 2023-02-24 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformance',
            name='questions_answered',
        ),
        migrations.RemoveField(
            model_name='userperformance',
            name='questions_correct',
        ),
        migrations.AddField(
            model_name='userperformance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='score_percentage',
            field=models.FloatField(default=0),
        ),
    ]
