# Generated by Django 3.2.17 on 2023-03-06 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20230224_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('question_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questionpack')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizsubject')),
            ],
        ),
    ]
