# Generated by Django 3.2.17 on 2023-03-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='prompts',
        ),
    ]
